# Generated by Django 2.2.1 on 2019-05-16 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190517_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='solved_puzzles',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_solved_by', to='puzzle.puzzle'),
        ),
    ]
