# Generated by Django 2.2.1 on 2019-05-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0013_auto_20190517_0055'),
        ('users', '0003_auto_20190517_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='solved_puzzles',
        ),
        migrations.AddField(
            model_name='user',
            name='solved_puzzles',
            field=models.ManyToManyField(blank=True, default=1, null=True, related_name='puzzle_solved_by', to='puzzle.puzzle'),
        ),
    ]
