# Generated by Django 2.2.1 on 2019-05-16 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0013_auto_20190517_0055'),
        ('users', '0004_auto_20190517_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='solved_puzzles',
        ),
        migrations.AddField(
            model_name='user',
            name='last_solved_puzzle',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_solved_by', to='puzzle.puzzle'),
        ),
    ]
