# Generated by Django 2.2.1 on 2019-05-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190525_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_solved_puzzle',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_solved_by', to='puzzle.puzzle'),
        ),
    ]
