# Generated by Django 2.2.1 on 2019-05-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_title', models.TextField()),
                ('puzzle_image', models.ImageField(upload_to='')),
                ('puzzle_description', models.TextField()),
                ('puzzle_password', models.TextField()),
            ],
        ),
    ]
