# Generated by Django 2.2.1 on 2019-05-11 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='next_puzzle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_previous_puzzle', to='puzzle.puzzle'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='previous_puzzle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_next_puzzle', to='puzzle.puzzle'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_image',
            field=models.ImageField(upload_to='puzzle_images'),
        ),
    ]
