# Generated by Django 2.2.1 on 2019-05-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0003_auto_20190511_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_url',
            field=models.URLField(default='127.0.0.1'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_image',
            field=models.ImageField(blank=True, upload_to='puzzle_images'),
        ),
    ]
