# Generated by Django 2.2.1 on 2019-05-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0006_auto_20190517_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='hint_password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='puzzle_hinted_password',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_hinted_password',
            field=models.ManyToManyField(to='puzzle.hint_password'),
        ),
    ]
