# Generated by Django 2.2.1 on 2019-05-16 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0008_auto_20190517_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='wrong_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_page_url', models.URLField()),
                ('wrong_page_title', models.CharField(blank=True, max_length=30)),
                ('wrong_page_description', models.TextField(blank=True)),
                ('wrong_page_image', models.ImageField(upload_to='wrong_page_images')),
            ],
        ),
        migrations.AlterField(
            model_name='hint_password',
            name='hinted_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='puzzle.wrong_page'),
        ),
    ]
