# Generated by Django 2.2.1 on 2019-05-16 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0009_auto_20190517_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint_password',
            name='hinted_page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzle.wrong_page'),
        ),
    ]
