# Generated by Django 2.2.1 on 2019-05-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0010_auto_20190517_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrong_page',
            name='wrong_page_url',
            field=models.URLField(blank=True),
        ),
    ]
