# Generated by Django 2.2.1 on 2019-05-16 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0011_auto_20190517_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrong_page',
            name='wrong_page_url',
        ),
    ]
