# Generated by Django 2.2.1 on 2019-05-23 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0015_auto_20190523_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='next_puzzle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_previous_puzzle', to='puzzle.puzzle'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='previous_puzzle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_next_puzzle', to='puzzle.puzzle'),
        ),
    ]
