# Generated by Django 2.2.1 on 2019-05-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0017_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_audio',
            field=models.FileField(blank=True, upload_to='puzzle_audios'),
        ),
    ]
