# Generated by Django 2.2.1 on 2019-05-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0021_puzzle_puzzle_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_image_width_height',
            field=models.IntegerField(default=100),
        ),
    ]
