# Generated by Django 2.2.1 on 2019-05-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0022_puzzle_puzzle_image_width_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_created_time',
            field=models.DateTimeField(),
        ),
    ]
